# Generated by Django 4.2.7 on 2025-08-20 15:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('message', 'Message'), ('comment', 'Comment'), ('live_comment', 'Live Comment'), ('mention', 'Mention')], max_length=20)),
                ('platform', models.CharField(choices=[('facebook', 'Facebook'), ('instagram', 'Instagram')], max_length=10)),
                ('page_id', models.CharField(max_length=100)),
                ('sender_id', models.CharField(blank=True, max_length=100, null=True)),
                ('message_text', models.TextField(blank=True, null=True)),
                ('comment_text', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField()),
                ('raw_data', models.JSONField()),
                ('thank_you_sent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ThankYouMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('webhook_event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='webhooks.webhookevent')),
            ],
        ),
    ]
